### ISSUE TITLE
Add .gitattributes

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/panda#3]
Add a .gitattributes file with the proper declarations for CRLF text files.  Issue raised by @bictorv.

**Comment by larsbrinkhoff** [comment]
These are all the type types currently found in this repository:

 File type | Data type |
| --- | ---
| . |
| .04 |
| .1 |
| .10 |
| .2 |
| .2x1 |
| .3 |
| .4 |
| .5-4-dif | Text diff?
| .58 |
| .6-1-red |
| .abs |
| .add |
| .address |
| .adx |
| .aff |
| .ann |
| .announcement | Text file.
| .apl | APL source code?
| .archive |
| .ato |
| .atr |
| .aux |
| .b20 |
| .b36 |
| .bar |
| .bcp | BCPL source code.
| .bib |
| .bin | Binary data.
| .bli | BLISS source code.
| .bpr |
| .brack |
| .bsy |
| .bug |
| .bus |
| .bwr | Text file.
| .c | C source code.
| .card |
| .cbl |
| .ccl | Script.
| .ccl-orig | Script.
| .changes | Text file.
| .chart | Text file.
| .chg |
| .cis |
| .cld |
| .clisp | Lisp source code.
| .cmd | Script.
| .cmds |
| .cmp |
| .code |
| .c-old |
| .com |
| .compare | Text diff?
| .compiler-edit-history |
| .comprs |
| .config |
| .cont |
| .c-orig | C source code.
| .c-save | C source code?
| .csi |
| .ctl |
| .ctx |
| .cx1 |
| .d |
| .dat |
| .datatype |
| .dbg |
| .dct |
| .defn |
| .defns |
| .dev |
| .dictionary |
| .dif | Text diff?
| .dir | Directory listing?
| .dis |
| .doc | Text file.
| .doc-orig | Text file.
| .edt |
| .^V:ej | Compiled EMACS/TECO code.  Maybe text?
| .el | Emacs Lisp source code.
| .elc | Emacs Lisp compiled code.  Text.
| .el-orig | Emacs Lisp source code.
| .emacs | EMACS init file.
| .err |
| .errors |
| .exb |
| .exe | Binary executable.
| .eye |
| .fai | FAIL source code.
| .fasl | Lisp compiled code.
| .fil |
| .files |
| .flags |
| .flg |
| .float |
| .fnc |
| .fnt |
| .fon |
| .for | Fortran source code.
| .fun |
| .gateways |
| .ggb |
| .glb |
| .guide |
| .h | C source code.
| .hairy |
| .hash |
| .hdr |
| .help | Text file.
| .his |
| .hlb |
| .hlp |
| .h-orig | C source code.
| .how-to-load | Text file.
| .hp |
| .i |
| .idx |
| .index |
| .info | Text file.
| .ini |
| .init |
| .init-for-ledit |
| .ins |
| .install |
| .int |
| .introduction |
| .invoke |
| .kcc |
| .kcm |
| .key |
| .keys |
| .kys |
| .l36 |
| .lap | Lisp assembler code.  Text?
| .ledit-init |
| .lib |
| .lines |
| .lis |
| .lisp | Lisp source code.
| .lisp16 |
| .lnk |
| .lns |
| .log | Log file: text.
| .logo | Logo source code?
| .losses |
| .lsb |
| .lsp |
| .lst |
| .lus |
| .mac | MACRO source code.
| .mail | Text file.
| .mak | Makefile.
| .man | Text file.
| .manual | Text file.
| .map |
| .mar |
| .maze |
| .mem | Text file.
| .memos |
| .mhlc-doc |
| .mic |
| .mic-orig |
| .mid |
| .missingfunctionslist |
| .mlb |
| .mpr |
| .msc |
| .msg | Text file.
| .mss | Text file.
| .msx |
| .msy |
| .mtb |
| .nameservers |
| .newhash |
| .nic |
| .note | Text file.
| .notice | Text file.
| .nul |
| .num |
| .obj |
| .old |
| .opr |
| .ops |
| .opt |
| .ovars |
| .owners |
| .pad |
| .panda |
| .pas | Pascal source code.
| .pic |
| .pl | Perl source code.
| .poi |
| .ports |
| .pos |
| .pre |
| .press |
| .primer |
| .pro |
| .profile |
| .protocols |
| .ps |
| .quasar |
| .que |
| .qwabl |
| .r36 |
| .ram |
| .rcw1 |
| .ref |
| .refcard |
| .reference |
| .reference-card |
| .rel |
| .release |
| .req |
| .rmc |
| .rnd |
| .rnh |
| .rnm |
| .rno | Runoff source file.
| .rpt |
| .run |
| .sai | SAIL source code.
| .sav | Binary executable.
| .seq |
| .servers |
| .share |
| .shf |
| .sho |
| .shr | Binary executable.
| .sim |
| .simple |
| .skel |
| .spe |
| .spt |
| .statistics |
| .sup |
| .symbols | Binary symbol table.
| .syn |
| .syntax |
| .sys |
| .t20 |
| .t20-orig |
| .tac |
| .tarz |
| .tc |
| .tcd |
| .tco |
| .tec | TECO source code?
| .teco | TECO source code.
| .tfo |
| .-this- | Text file.
| .tpe |
| .tty |
| .txt | Text file.
| .uld |
| .umacs |
| .unix |
| .unv | Binary universal file.
| .upd |
| .use-mmailr |
| .usr |
| .utility-overlays-1 |
| .utility-overlays-2 |
| .vars |
| .vax-cob |
| .ver |
| .verify |
| .vfu |
| .vfy |
| .vms | Not a full DEC.
| .vts |
| .wall-chart |
| .wide-chart |
| .xct |
| .xforms |
| .y |

**Comment by bictorv** [comment]
It might be helpful to check the byte sizes of the files?

**Comment by larsbrinkhoff** [comment]
Yes, that would be a good indication.

I just added this: https://github.com/PDP-10/panda/pull/4 which should take care of the most important file types.
